spring:
  datasource:
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/customer
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  port: 0
  error:
    include-message: always
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  
